#!/bin/bash -ex

fatal() {
    echo "fatal: $@" 1>&2
    exit 1
}

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

case "$FAB_ARCH" in
    i386)  
        VERSION="go_appengine_sdk_linux_386-1.7.5.1.zip"
        SHA1SUM="64de98afa0acb606f9a8b8dc3ebd9a97372bdbf4"
        ;;
    amd64) 
        VERSION="go_appengine_sdk_linux_amd64-1.7.5.1.zip"
        SHA1SUM="cf064296ae3b80ce64c48b6d03132a36718efd4a"
        ;;
    *) 
        fatal "FAB_ARCH is not set or not recognized"
        ;;
esac

SRC=/usr/local/src

dl http://googleappengine.googlecode.com/files/${VERSION} $SRC

echo "$SHA1SUM  $VERSION" > $SRC/$VERSION.sha1
cd $SRC; sha1sum -c $VERSION.sha1; rm $VERSION.sha1; cd -

