#!/bin/bash -ex

fatal() {
    echo "fatal: $@" 1>&2
    exit 1
}

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

case "$FAB_ARCH" in
    i386)  
        VERSION="go_appengine_sdk_linux_386-1.7.7.zip"
        SHA1SUM="8055b757c517c1d910139470c2dd3a12ea0e0c49"
        ;;
    amd64) 
        VERSION="go_appengine_sdk_linux_amd64-1.7.7.zip"
        SHA1SUM="c53b275beb9ca6b4816c6b7d3df68cf7f5208e19"
        ;;
    *) 
        fatal "FAB_ARCH is not set or not recognized"
        ;;
esac

SRC=/usr/local/src

dl http://googleappengine.googlecode.com/files/${VERSION} $SRC

echo "$SHA1SUM  $VERSION" > $SRC/$VERSION.sha1
cd $SRC; sha1sum -c $VERSION.sha1; rm $VERSION.sha1; cd -

